// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-0bJIoynUtMassGUTlo7IPbwUUUOO_uM',
    appId: '1:7725067660:web:2d8b7b107c98ae92cf7aa9',
    messagingSenderId: '7725067660',
    projectId: 'fir-ea78d',
    authDomain: 'fir-ea78d.firebaseapp.com',
    storageBucket: 'fir-ea78d.appspot.com',
    measurementId: 'G-NY09J99897',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3uLc4r-mw_Gbo4uLRAZqAAKqRzydIAKw',
    appId: '1:7725067660:android:23b1f772409120b6cf7aa9',
    messagingSenderId: '7725067660',
    projectId: 'fir-ea78d',
    storageBucket: 'fir-ea78d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdn308vRVQ_svb916XOajjhywuWCsb_jY',
    appId: '1:7725067660:ios:4a6ef6f1b6f9ceeacf7aa9',
    messagingSenderId: '7725067660',
    projectId: 'fir-ea78d',
    storageBucket: 'fir-ea78d.appspot.com',
    iosBundleId: 'com.lenovo.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdn308vRVQ_svb916XOajjhywuWCsb_jY',
    appId: '1:7725067660:ios:9006936032eb446acf7aa9',
    messagingSenderId: '7725067660',
    projectId: 'fir-ea78d',
    storageBucket: 'fir-ea78d.appspot.com',
    iosBundleId: 'com.lenovo.firebase.RunnerTests',
  );
}
